### ISSUE TITLE
waiting for local node.

### ISSUE THREAD

**Issue by whit2333** [JeffersonLab/clara-demo#1]
Following the instructions, the processing hangs...

```
clara> run local
Distribution  :    clara-cre-4.3.5
CLAS12 plugin :    coatjava-5.7.4

==========================================
               CLARA FE/DPE               
==========================================
 Name             = 172.17.0.1%7300_java
 Session          = whit_clara
 Start time       = 2019-02-11 20:34:45
 Version          = 4.3
 Lang             = Java
 Pool size        = 2

 Proxy Host       = 172.17.0.1
 Proxy Port       = 7300
==========================================
==========================================
            CLARA Orchestrator            
==========================================
 Front-end          = 172.17.0.1%7300_java
 Start time         = 2019-02-11 20:34:49
 Threads            = 2

 Input directory    = /mnt/old_home/whit/projects/clara/clara-demo/resources
 Output directory   = /tmp/out
 Output file prefix = out_
 Number of files  = 1
==========================================
2019-02-11 20:34:49.283: Waiting for local node...
2019-02-11 20:35:49.441: Could not run data processing!
2019-02-11 20:35:49.441: could not find a data processing node
2019-02-11 20:35:49.442: Exiting...
```

This is the same message I got when using with clas12 reconstruction.

**Comment by smancill** [comment]
The C++ DPE is not starting. Probably installed somewhere else and not in `$CLARA_HOME`.

The CLARA C++ implementation currently needs to be installed in the same `$CLARA_HOME` than the Java distribution (just like the services in this project).

The install prefix when compiling xmsg-cpp/clara-cpp should be configured as:

    cmake -DCMAKE_INSTALL_PREFIX=$CLARA_HOME ..

Your third party dependencies (OpenCV, evio, hipo, etc) would be best installed somewhere else and then added to `LD_LIBRARY_PATH`.

The shell is just  a wrapper. You can also try https://github.com/JeffersonLab/clara-demo#starting-the-clara-dpes-and-orchestrator-manually to check if everything runs.

And I am the developer of the C++ implementation, but I am not part of the CLAS collaboration anymore and you should't expect much support.

**Comment by whit2333** [comment]
Wow thanks for the quick reply. Yes. I installed the xmsg-cpp to somewhere else earlier. It continued to find it when building clara-cpp so I sort of forgot about that dependency.

I installed xmsg-cpp in $CLARA_HOME and everything appeared to work. 

Thank you!
